---
title: "Untitled"
author: "Sunny"
date: "2020/9/5"
output: html_document
---

```{r}
library(dplyr)
library(ggcal)
library(knitr)
library(lubridate)
```

```{r}
#取出事件、開始時間、結束時間
data.frame(ntpuEvents[["items"]][["summary"]],ntpuEvents[["items"]][["start"]][["date"]],ntpuEvents[["items"]][["end"]][["date"]])-> ntpuEvents_time
```

```{r}
#變更名稱
colnames(ntpuEvents_time)<-c("Events","Start","End")
ntpuEvents_time

#按時間遞增排序
ntpuEvents_time%>%
  arrange(Start)-> ntpuEvents_time
ntpuEvents_time

#改變屬性
ymd(ntpuEvents_time$Start)->ntpuEvents_time$Start
ymd(ntpuEvents_time$End)->ntpuEvents_time$End

#分出各類事件
grep("考",ntpuEvents_time$Events)->row_test
grep("選課",ntpuEvents_time$Events)->row_class
grep("新生",ntpuEvents_time$Events)->row_fresh
grep("假",ntpuEvents_time$Events)->row_holiday

#選出各類事件
ntpuEvents_time[c(row_test),]->ntpuEvents_time_test
ntpuEvents_time[c(row_class),]->ntpuEvents_time_class
ntpuEvents_time[c(row_fresh),]->ntpuEvents_time_fresh
ntpuEvents_time[c(row_holiday),]->ntpuEvents_time_holiday

ntpuEvents_time_test%>%
  mutate(
    Category="考試"
  )->ntpuEvents_time_test

```


```{r}
library(ggplot2)
library(ggcal)

mydate <- seq(as.Date("2020-08-01"), as.Date("2021-08-31"), by="1 day")
myfill_test <- ntpuEvents_time_test$Start

print(ggcal(ntpuEvents_time_test$Start, ntpuEvents_time_test$Category))
```


```{r}
devtools::install_github("gadenbuie/ggweekly")

# create a calendar for April, May and June
library(ggweekly)
ggweek_planner(
  start_day = "2020-08-01", 
  end_day = "2020-08-31", 
)
```

```{r}
library(tidyverse)
library(dplyr)
library(purrr)
library(tidyr)
library(forcats)
library(ggplot2)
library(lubridate)
```

```{r}
#每周從星期一開始
options("lubridate.week.start" = 1)
```

```{r}
start_day <- floor_date(ymd("2019-06-24"), "week")
end_day   <- ymd("2019-08-16")
seq_days  <- seq(start_day, end_day, by = "day")

seq_days[1:5]
```

```{r}
dates <-
  tibble(
    day       = seq_days,
    wday_name = wday(day, label = TRUE, abbr = TRUE), #找出星期幾 1是週一 7是週日
    weekend   = wday(day) > 5,
    isoweek   = isoweek(day),
    month     = month(day, label = TRUE, abbr = FALSE),
    isoyear   = isoyear(day),
    week_year = fct_rev(sprintf("%s - %s", isoyear, isoweek)) 
  )
#fct_rev使week_year成為factor並反轉factor順序，使Y軸往下可以由小到大
dates
```

```{r}
dates %>% pull(week_year) %>% levels() %>% tail()
```

```{r}
day_one <- dates %>% 
  filter(day(day) == 1)

day_one
```
```{r}
week_start_labels <- dates %>%
  filter(wday_name == "Mon") %>% 
  arrange(day) %>%
  mutate(
    month = month(day, label = TRUE), 
    label = case_when(
      month == lag(month) ~ paste(day(day)),
      TRUE ~ sprintf("%s %4i", month, day(day))
    )
  ) %>% 
  select(label, week_year) %>% 
  reduce(setNames)
```

```{r}
highlight_days <- tribble(
         ~ day,            ~ label,   ~ color,    ~ fill,
  "2019-07-02", "Project Kick Off", "#02307a", "#02307a",
  "2019-07-04",         "July 4th", "#b4436c", "#b4436c",
  "2019-07-12",          "LOI Due", "#02307a", "#02307a",
  "2019-07-26",      "First Draft", "#02307a", "#02307a",
  "2019-08-05",        "Work week", "#02307a", "#02307a",
  "2019-08-06",                 "",        NA, "#02307a",
  "2019-08-07",                 "",        NA, "#02307a",
  "2019-08-08",                 "",        NA, "#02307a",
  "2019-08-09",                 "",        NA, "#02307a",
  "2019-08-16", "Final Submission", "#02307a", "#02307a"
) %>% 
  mutate_at(vars(day), ymd)
```

```{r}
gcal <-
  dates %>% 
  mutate(
    # Softly fill in the weekend days
    weekend = case_when(weekend ~ "#f8f8f8", TRUE ~ "#FFFFFF")
  ) %>% 
  ggplot() +
  aes(wday_name, week_year) +
  # the calendar grid
  geom_tile(aes(fill = weekend), color = "#aaaaaa") +
  # highlight first day of each month
  geom_tile(
    data = day_one,
    fill = "#f78154",
    alpha = 0.25
  ) +
  # add name of month to the first day
  geom_text(
    data = day_one, 
    aes(label = month),
    family = "PT Sans Narrow",
    color = "#f78154",
    size = 4,
    # push text to the top left corner
    hjust = 0,
    nudge_x = -0.45,
    vjust = 1,
    nudge_y = 0.45
  ) +
  # highlight project-specific days
  geom_tile(
    data = dates %>% inner_join(highlight_days, by = "day"),
    aes(fill = fill),
    alpha = 0.25
  ) +
  # add the label from the highlighted days
  geom_text(
    data = dates %>% inner_join(highlight_days, by = "day"),
    aes(label = label, color = color),
    family = "PT Sans Narrow",
    size = 2,
    # push to bottom left corner
    hjust = 0,
    nudge_x = -0.45,
    vjust = 0,
    nudge_y = -0.40
  ) +
  scale_x_discrete(position = "top") +
  scale_y_discrete(labels = week_start_labels) +
  scale_fill_identity() +
  scale_color_identity() +
  guides(fill = FALSE) +
  theme_minimal(base_family = "PT Sans") +
  theme(
    axis.text = element_text("PT Sans Narrow"),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    axis.text.x.top = element_text(face = "bold"),
    axis.title.x.top = element_blank(),
  )

gcal
```

```{r}
ggweek_planner(
  start_day = "2020-08-01", 
  end_day = "2020-12-31", 
  show_month_boundaries = FALSE, 
  show_month_start_day = FALSE,
  week_start = "isoweek",
  week_start_label = "week"
) + 
  ggplot2::ggtitle("2020") +
  ggplot2::facet_wrap(~ month, scales = 'free')
```

